GET http://localhost:50052/health

###

GET http://localhost:50052/items

###

POST http://localhost:50052/items
Content-Type: application/json

{
  "key": "foo",
  "value": "bar"
}

###

GET http://localhost:50052/items/foo

###

PUT http://localhost:50052/items/foo
Content-Type: application/json

{
  "value": "baz"
}

###

DELETE http://localhost:50052/items/foo